In [1]:
#### zeros():괄호 안에 입력된 숫자만큼의 원소를 생성하고
0 으로 초기화

SyntaxError: invalid character in identifier (<ipython-input-1-7cfc21ae7b30>, line 3)

In [17]:
import numpy as np

# y = np.zeros(shape=(10,2), dtype=np.int8)
y = np.zeros(10)
y


# print(y)

# x = np.array([1,2,3])
# type(x)
# x.shape



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
#### mean():배열에 저장된 원소들의 평균값을 계산

In [ ]:
import numpy as np

list_1 = [1,2,3]
x = np.array(list_1)
np.mean(x)
x.mean()
x.shape

#### array():Numpy 형식으로 배열의 원소를 입력할 때는 반드시
리스트 형식으로 입력

x = np.array([1,2,3])
y = np.array([1,2,3])
ptint(x,y)

In [ ]:
x = np.array([1,2,3]) 
y = np.array([1,2,3])
z = np.array([1,2.3])
a = np.array([{'a':'b','a':'b'}) 
ptint(x,y z,a)

#### reshape():배열을 원하는 모양으로 생성

In [ ]:
import numpy as np
a = [1,2,3,4,5,6,7,8]
b = np.reshape(a,(2,4))
c = np.reshape(a,(4,2))
print(b, b.shape, c, '\n' ,c.shape)

In [9]:
a = np.arange(1,9)
print(a)
b = a.reshape(2,2,2)
print(b)

[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
x.reshape(-1,11)

ValueError: cannot reshape array of size 4 into shape (11)

In [14]:
x.reshape(-1,3)

ValueError: cannot reshape array of size 4 into shape (3)

#### ones():배열을 1 의 값들로 채움

In [18]:
y = np.ones([3,10])
print(y)

x = np.ones([5,5])
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### 배열의 슬라이싱

In [19]:
list1 = [[1,11], [2,12], [3,13], [4,14]]
print(list1[:][1])

[2, 12]


In [26]:
list = [[1,11], [2,12], [3,13], [4,14]]
array = np.array(list)
print(np_ary[:,1])

[11 12 13 14]


#### 파이썬 math 모듈의 sqrt 와 numpy 모듈의 sqrt 비교

In [27]:
import math
math.sqrt(2)

1.4142135623730951

In [28]:
import numpy as np
np.sqrt([2,3,4])

array([1.41421356, 1.73205081, 2.        ])

In [29]:
import numpy as np
np.sqrt(2)

1.4142135623730951

In [30]:
import numpy as np
np.sqrt(2)
np.sqrt([2,3,4])

array([1.41421356, 1.73205081, 2.        ])

In [31]:
import numpy as np
np.sqrt([2,3,4,5,6,7,8])

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131, 2.82842712])

In [32]:
import math
math.sqrt([2,3,4,5,6])

TypeError: must be real number, not list

In [12]:
import numpy as np
zero_vector = np.zeros(5)
print(zero_vector)


[0. 0. 0. 0. 0.]


In [14]:
zero_matrix = np.zeros((4, 3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
zero_vector = np.zeros(5)
print(zero_vector)

[0. 0. 0. 0. 0.]


In [19]:
y = np.zeros((5,3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
y = np.zeros((5,3))
z = y.reshape((3,5))
z+=4
print(z)

[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]


### 전치행렬 transpose: 행과 열을 바꾸는 행렬. (ex, 2*4은 4*2로)

In [27]:
import numpy as np
ary = np.array([[1,2], [3,4]])
print(ary)

trans_ary = ary.transpose()
print(trans_ary)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [29]:
ary = np.array([[1,2,5], [3,4,6]])
print(ary)

trans_ary = ary.transpose()
print(trans_ary)

[[1 2 5]
 [3 4 6]]
[[1 3]
 [2 4]
 [5 6]]


### 사칙연산 

In [34]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
print (x+y)
print (x*y)
print (x/y)
print (x**y)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [41]:
x = np.array([1,2,3])
x +=20
print(x)


[21 22 23]


### 인덱싱

In [47]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x[1])
print(x[:,1])

[4 5 6]
[2 5 8]


In [50]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(x[1])
print(y[:,3])

[5 6 7]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [51]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(x[0,:]+y[2,:])

[ 9 11 13]


In [52]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(x[1,:]+y[1,:])

[ 9 11 13]


In [54]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(x[2,:]+y[2,:])

[15 17 19]


In [55]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(x[:,2]*y[3,:])

IndexError: index 3 is out of bounds for axis 0 with size 3

In [58]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(x[:,1]*y[2,:])

[16 45 80]


In [59]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(x[:,2]+y[2,:])

[11 15 19]


In [60]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(x[:,0]+y[0,:])

[ 3  7 11]


In [63]:
a = np.array([100,20,30,40,50])
b = a>30
print(b)

[ True False False  True  True]


### random

In [67]:
import numpy as np
a = np.random.random(5)
print(a)

[0.02957452 0.54126526 0.00228442 0.18576314 0.54481974]


In [66]:
b = np.random.rand(2, 3)
print(b)

[[0.38487091 0.14165261 0.69307132]
 [0.48236056 0.60899752 0.22551668]]


In [68]:
# 메소드에 입력값으로 5 를 입력해주면 0 에서 1사이의 무작위의 수 5 개를 생성
a = np.random.rand(5)
print(a)

b = np.random.rand(2, 3)
print(b , b.shape)

[0.15062509 0.51163307 0.06441043 0.87683462 0.27769101]
[[0.20196387 0.35731097 0.10855755]
 [0.43509433 0.45319297 0.91966475]] (2, 3)


In [71]:
a = np.random.randint(10, size=5)
print(a)

b = np.random.randint(2, 10, size=6)
print(b)

c = np.random.randint(1, 5, size=(2, 3))
print(c)

[8 5 4 5 4]
[4 4 2 9 3 3]
[[1 2 2]
 [3 4 3]]


### random.seed:함수는 난수 생성에 필요한 시드를 설정합니다.

In [93]:
import numpy as np

np.random.seed(0)

print(np.random.rand(2, 3))

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]


In [94]:
np.random.seed(0)
a = np.random.rand(5)
a>0.12

array([ True,  True,  True,  True,  True])

### any() 와 all() 의 비교


import numpy as n
a = np.random.rand(5)
print(a>0.12)
print(na.all(a>0.12))

In [144]:
a = np.random.rand(5)
print(a>0.12)
print(np.any(a>0.12))

[ True  True  True  True  True]
True


In [160]:
a = np.random.rand(5)
print(a)
print(np.all(a >=0.3))
print(np.any(a>0.7))


[0.18115096 0.78854551 0.05684808 0.69699724 0.7786954 ]
False
True


### linspace():시작과 끝의 값을 지정하고 그 사이의 값을 균등하게 배분

In [163]:
np.linspace(1,13,5)

array([ 1.,  4.,  7., 10., 13.])

In [164]:
np.linspace(0,12,4, endpoint=False)

array([0., 3., 6., 9.])

In [166]:
np.linspace(0,12,4, retstep=True)

(array([ 0.,  4.,  8., 12.]), 4.0)